"""Distributed primitive protocols and backend implementations."""

from __future__ import annotations

from core_py.dkit.errors import (
    ERR_ALREADY_UNLOCKED,
    ERR_BACKEND_UNAVAILABLE,
    ERR_CODE_DKIT_ALREADY_UNLOCKED,
    ERR_CODE_DKIT_BACKEND_UNAVAILABLE,
    ERR_CODE_DKIT_DEFAULT_KIT_NOT_CONFIGURED,
    ERR_CODE_DKIT_ELECTION_NOT_ENABLED,
    ERR_CODE_DKIT_INVALID_OPTION,
    ERR_CODE_DKIT_LOCK_NOT_ACQUIRED,
    ERR_CODE_DKIT_NO_AVAILABLE_NUMBER,
    ERR_DEFAULT_KIT_NOT_CONFIGURED,
    ERR_ELECTION_NOT_ENABLED,
    ERR_INVALID_OPTION,
    ERR_LOCK_NOT_ACQUIRED,
    ERR_NO_AVAILABLE_NUMBER,
    AlreadyUnlockedError,
    BackendUnavailableError,
    DefaultKitNotConfiguredError,
    DKitError,
    ElectionNotEnabledError,
    InvalidOptionError,
    LockNotAcquiredError,
    NoAvailableNumberError,
)
from core_py.dkit.kit import (
    SNOWFLAKE_START_TIME,
    Action,
    DefaultKit,
    Kit,
    SnowflakeIDGenerator,
    default_kit,
    new_default_kit,
    reset_default_kit,
    set_default_kit,
    use_default_kit,
)
from core_py.dkit.memory import InMemoryAtomic, InMemoryMutex
from core_py.dkit.mongo import MongoAtomic, MongoMutex
from core_py.dkit.options import (
    DEFAULT_ELECTION_TIMEOUT,
    DEFAULT_ELECTION_UNHEALTHY_TIME,
    DEFAULT_LOCK_SPIN_INTERVAL,
    DEFAULT_LOCK_TTL,
    ElectionOption,
    ElectionOptionOp,
    LeaderChangedEvent,
    LeaderChangedHandler,
    LockOption,
    LockOptionOp,
    lock_ttl,
    lock_with_max_wait,
    lock_with_spin_interval,
    new_lock_option,
    reentrant,
)
from core_py.dkit.protocols import Atomic, DistributedMutex, ElectionController
from core_py.dkit.redis import RedisAtomic, RedisMutex

__all__ = [
    "Action",
    "AlreadyUnlockedError",
    "Atomic",
    "BackendUnavailableError",
    "DKitError",
    "DEFAULT_ELECTION_TIMEOUT",
    "DEFAULT_ELECTION_UNHEALTHY_TIME",
    "DEFAULT_LOCK_SPIN_INTERVAL",
    "DEFAULT_LOCK_TTL",
    "DefaultKitNotConfiguredError",
    "DefaultKit",
    "DistributedMutex",
    "ERR_ALREADY_UNLOCKED",
    "ERR_BACKEND_UNAVAILABLE",
    "ERR_CODE_DKIT_ALREADY_UNLOCKED",
    "ERR_CODE_DKIT_BACKEND_UNAVAILABLE",
    "ERR_CODE_DKIT_DEFAULT_KIT_NOT_CONFIGURED",
    "ERR_CODE_DKIT_ELECTION_NOT_ENABLED",
    "ERR_CODE_DKIT_INVALID_OPTION",
    "ERR_CODE_DKIT_LOCK_NOT_ACQUIRED",
    "ERR_CODE_DKIT_NO_AVAILABLE_NUMBER",
    "ERR_DEFAULT_KIT_NOT_CONFIGURED",
    "ERR_ELECTION_NOT_ENABLED",
    "ERR_INVALID_OPTION",
    "ERR_LOCK_NOT_ACQUIRED",
    "ERR_NO_AVAILABLE_NUMBER",
    "ElectionController",
    "ElectionNotEnabledError",
    "ElectionOption",
    "ElectionOptionOp",
    "InMemoryAtomic",
    "InMemoryMutex",
    "InvalidOptionError",
    "Kit",
    "LeaderChangedEvent",
    "LeaderChangedHandler",
    "LockNotAcquiredError",
    "LockOption",
    "LockOptionOp",
    "MongoAtomic",
    "MongoMutex",
    "NoAvailableNumberError",
    "RedisAtomic",
    "RedisMutex",
    "SNOWFLAKE_START_TIME",
    "SnowflakeIDGenerator",
    "default_kit",
    "lock_ttl",
    "lock_with_max_wait",
    "lock_with_spin_interval",
    "new_default_kit",
    "new_lock_option",
    "reset_default_kit",
    "reentrant",
    "set_default_kit",
    "use_default_kit",
]
