"""Protocols for distributed primitives."""

from __future__ import annotations

from typing import Protocol

from core_py import context as ctx_mod
from core_py.dkit.options import ElectionOption, LockOptionOp


class DistributedMutex(Protocol):
    def lock(self, ctx: ctx_mod.Context | None = None, *ops: LockOptionOp) -> None: ...
    def try_lock(self, ctx: ctx_mod.Context | None = None, *ops: LockOptionOp) -> bool: ...
    def unlock(self, ctx: ctx_mod.Context | None = None) -> None: ...
    def exist_lock(self, ctx: ctx_mod.Context | None = None) -> bool: ...


class ElectionController(Protocol):
    def enable_election(self, opt: ElectionOption | None = None) -> None: ...
    def node_key(self) -> str: ...
    def is_leader(self) -> bool: ...
    def alive_nodes(self) -> list[str]: ...
    def is_alive(self, node_key: str) -> bool: ...


class Atomic(ElectionController, Protocol):
    def get_unique_random_number(self, ctx: ctx_mod.Context | None, max_value: int) -> int: ...
    def new_mutex(self, key: str) -> DistributedMutex: ...
    def get_mutex_default_ttl(self) -> float: ...
    def close(self) -> None: ...
