"""Protocols for distributed primitives."""

from __future__ import annotations

from typing import Protocol

from core_py.dkit.options import ElectionOption, LockOptionOp


class DistributedMutex(Protocol):
    async def lock(self, *ops: LockOptionOp) -> None: ...
    async def try_lock(self, *ops: LockOptionOp) -> bool: ...
    async def unlock(self) -> None: ...
    async def exist_lock(self) -> bool: ...


class ElectionController(Protocol):
    async def enable_election(self, opt: ElectionOption | None = None) -> None: ...
    def node_key(self) -> str: ...
    async def is_leader(self) -> bool: ...
    async def alive_nodes(self) -> list[str]: ...
    async def is_alive(self, node_key: str) -> bool: ...


class Atomic(ElectionController, Protocol):
    async def get_unique_random_number(self, max_value: int) -> int: ...
    def new_mutex(self, key: str) -> DistributedMutex: ...
    def get_mutex_default_ttl(self) -> float: ...
    async def close(self) -> None: ...
