"""Domain model helpers: entities, audit fields and repository options."""

from core_py.model.audit import (
    CreateAudit,
    CreateAuditMs,
    DeleteAudit,
    DeleteAuditMs,
    TenantAudit,
    TenantCarrier,
    UpdateAudit,
    UpdateAuditMs,
    _missing_context_error,
    _now,
    _now_ms,
)
from core_py.model.entity import Entity
from core_py.model.options import (
    CTX_KEY_REPO_OPT,
    DATA_ISOLATION_APP,
    DATA_ISOLATION_NONE,
    DATA_ISOLATION_TENANT,
    DATA_ISOLATION_USER,
    DEPLOY_ISOLATION_CLUSTER,
    DEPLOY_ISOLATION_ENV,
    DEPLOY_ISOLATION_NONE,
    FIXED_STRATEGY_BACKOFF,
    FIXED_STRATEGY_NONE,
    SOFT_DELETE_DISABLE,
    SOFT_DELETE_ENABLE,
    UPDATE_RUN_CONTEXT_ALWAYS,
    UPDATE_RUN_CONTEXT_AT_CREATING,
    RepoOpt,
    UpdatesResult,
    audit,
    create_audit,
    delete_audit,
    merge_repo_opt,
    repo_opt_or_new,
    set_fixed_strategy,
    set_repo_data_isolation,
    set_repo_deploy_isolation,
    set_repo_update_run_context,
    set_soft_delete,
    update_audit,
    update_audit_and_env,
    update_lock_and_audit,
)
from core_py.model.page import FeedResult, PagedResult, Pager
from core_py.model.repo import Repo
from core_py.model.snowflake_id import SnowflakeID

__all__ = [
    "CTX_KEY_REPO_OPT",
    "CreateAudit",
    "CreateAuditMs",
    "DATA_ISOLATION_APP",
    "DATA_ISOLATION_NONE",
    "DATA_ISOLATION_TENANT",
    "DATA_ISOLATION_USER",
    "DEPLOY_ISOLATION_CLUSTER",
    "DEPLOY_ISOLATION_ENV",
    "DEPLOY_ISOLATION_NONE",
    "DeleteAudit",
    "DeleteAuditMs",
    "Entity",
    "FIXED_STRATEGY_BACKOFF",
    "FIXED_STRATEGY_NONE",
    "FeedResult",
    "PagedResult",
    "Pager",
    "Repo",
    "RepoOpt",
    "SOFT_DELETE_DISABLE",
    "SOFT_DELETE_ENABLE",
    "SnowflakeID",
    "TenantAudit",
    "TenantCarrier",
    "UPDATE_RUN_CONTEXT_ALWAYS",
    "UPDATE_RUN_CONTEXT_AT_CREATING",
    "UpdateAudit",
    "UpdateAuditMs",
    "UpdatesResult",
    "_missing_context_error",
    "_now",
    "_now_ms",
    "audit",
    "create_audit",
    "delete_audit",
    "merge_repo_opt",
    "repo_opt_or_new",
    "set_fixed_strategy",
    "set_repo_data_isolation",
    "set_repo_deploy_isolation",
    "set_repo_update_run_context",
    "set_soft_delete",
    "update_audit",
    "update_audit_and_env",
    "update_lock_and_audit",
]
