"""Repository protocols."""

from __future__ import annotations

from typing import Protocol, TypeVar

from core_py.model.snowflake_id import SnowflakeID

P = TypeVar("P", str, int, SnowflakeID)
T = TypeVar("T")


class Repo(Protocol[P, T]):
    async def get(self, id_: P) -> T: ...
    async def create(self, doc: T) -> T: ...
    async def update(self, doc: T) -> T: ...
    async def upsert(self, doc: T) -> T: ...
    async def patch(self, doc: T) -> None: ...
    async def delete(self, doc: T) -> None: ...
    async def batch_create(self, docs: list[T]) -> None: ...
    async def batch_update(self, docs: list[T]) -> None: ...
    async def batch_delete(self, docs: list[T]) -> tuple[int, None]: ...
    async def batch_delete_by_ids(self, ids: list[P]) -> tuple[int, None]: ...
